language: node_js
node_js:
  - "0.10"
  - "0.10"
services:
  - mysql
  - redis
before_install:
  - npm install -g forever
before_script:
  - git clone https://github.com/stellar/stellar-wallet.git
  - cd stellar-wallet
  - git checkout v2
  - npm install
  - NODE_ENV=test gulp db:setup
  - NODE_ENV=test forever start ./node_modules/stex/bin/stex www
  - cd ..
script:
  - npm run-script coverage
after_script:
  - gulp submit-coverage