ui: mocha-bdd
server: ./test/server.js
scripts:
  - "./build/stellar-wallet.js"
browsers:
  - name: chrome
    version: 37..latest
  - name: firefox
    version: 32..latest
  - name: ie
    version: 10..latest